name: Ansible

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Call REST API
      uses: swinton/httpie.action@1.0.6
      with:
        args: "POST https://d95ced56.ngrok.io/api/v2/job_templates/7/launch/ -a pseguel:ansible"
